---

- hosts: all
  become: true
  pre_tasks:

  - name: Install Apache (Ubuntu)
    apt:
      name:
        - apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install MySQL (Ubuntu)
    apt:
      name:
        - mysql-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: controller
  become: true
  roles:
    - Neutron
    - Horizon
    - Cinder
